[package]
name = "winget_cn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.18"
git2 = "0.18.1"
thiserror = "1.0.56"
